spring:
  application:
    name: stock-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  config:
    import: ${SPRING_CONFIG_IMPORT}
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
